### ISSUE TITLE
no links with static file cache

### ISSUE THREAD

**Issue by mithri** [featdd/dpn_glossary#140]
Hi there,

we are using the static file cache plugin. If the page is cached, the glossary links are not there. On the first load, before the page is cached (or if logged in in the backend) the links are working fine.

Any idea?

Thanks.
Tobias

**Comment by featdd** [comment]
There has been an issue with cached pages in general which was solved, the hook also should apply on normal cached pages in the latest versions.

I don't know if static file cache has an own way to create this pages where the hook does not apply, so the real issue may lies in static file cache, but as it is a very common extension I can test and my solve this if I do find the time for.

I'll leave this issue open, feel free to give me a hint or open a pull request :-)

Greetings
Daniel

**Comment by christophlehmann** [comment]
@mithri Is static file cache still an issue or does it work?

**Comment by featdd** [comment]
HI @mithri,

which static file cache extension/version did you use?

Greetings
Daniel

**Comment by featdd** [comment]
Could not reproduce this in the latest versions, will close this due to lack of feedback.
